name: Test
on:
  push:
    tags:
      - v*
  pull_request:
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: go test
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0'
          cache: false
      - run: go test -v ./...